# Generated by Django 5.0.4 on 2024-04-17 00:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pokemon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("national_number", models.BigIntegerField(max_length=200)),
                ("name", models.CharField(max_length=200)),
                ("type", models.CharField(max_length=200)),
            ],
        ),
    ]
