# Generated by Django 5.0.4 on 2024-04-27 02:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pokemon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("national_number", models.SmallIntegerField()),
                ("name", models.CharField(max_length=200)),
                ("type", models.CharField(max_length=200)),
                ("species", models.CharField(default="DEFAULT VALUE", max_length=200)),
                (
                    "height_meters",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "height_imperial",
                    models.CharField(default="DEFAULT VALUE", max_length=200),
                ),
                (
                    "weight_grams",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "weight_imperial",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "abilities",
                    models.CharField(default="DEFAULT VALUE", max_length=200),
                ),
            ],
        ),
    ]
