# Generated by Django 5.0.4 on 2024-04-18 01:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("national_dex", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokemon",
            name="abilities",
            field=models.CharField(default="DEFAULT VALUE", max_length=200),
        ),
        migrations.AddField(
            model_name="pokemon",
            name="height_imperial",
            field=models.CharField(default="DEFAULT VALUE", max_length=200),
        ),
        migrations.AddField(
            model_name="pokemon",
            name="height_meters",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pokemon",
            name="species",
            field=models.CharField(default="DEFAULT VALUE", max_length=200),
        ),
        migrations.AlterField(
            model_name="pokemon",
            name="national_number",
            field=models.SmallIntegerField(),
        ),
    ]
