# Generated by Django 5.0.4 on 2024-04-27 02:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("national_dex", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokemon",
            name="height_meters",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="pokemon",
            name="weight_grams",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="pokemon",
            name="weight_imperial",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
