# Generated by Django 5.0.4 on 2024-04-18 22:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("national_dex", "0002_pokemon_abilities_pokemon_height_imperial_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokemon",
            name="weight_grams",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="pokemon",
            name="weight_imperial",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="pokemon",
            name="height_meters",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
